import matplotlib.pyplot as plt
from PIL import Image
plt.rcParams['font.sans-serif']="SimHei"
img = Image.open("lena.tiff")
img.save("test.png")
img = Image.open("test.png")
img.thumbnail((250,250))
img_R,img_G,img_B = img.split()
plt.figure(figsize=(10,10))

plt.subplot(2,2,1)
plt.axis("off")
plt.imshow(img_R.resize((50,50)),cmap="gray")
plt.title("R-缩放",fontsize = 14)
plt.subplot(2,2,2)
#plt.xlim(0,200)
#plt.ylim(250,0)
img_G = img_G.transpose(Image.FLIP_LEFT_RIGHT)
img_G = img_G.transpose(Image.ROTATE_270)
plt.imshow(img_G,cmap="gray")
plt.title("G-镜像+旋转",fontsize=14)
plt.subplot(2,2,3)
img_B1 = img_B.crop((0,0,150,150))
plt.title("B-裁剪",fontsize = 14)
plt.axis("off")
plt.imshow(img_B1,cmap="gray")
plt.subplot(2,2,4)
img_rgb = Image.merge("RGB",[img_R,img_G,img_B])
plt.title("图像的色彩模式",fontsize = 14)
plt.axis("off")
plt.imshow(img_rgb)
plt.suptitle("图像基本操作",fontsize = 20,color="blue")
plt.show()
img_rgb.save("test.png")
